name: CI
on:
  push:
    branches:
      - docker
jobs:
              
  docker:
    runs-on: ubuntu-18.04
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: test
        run: |
        
          set -x
          
          docker build -t                   academiaonline/dca-phpinfo:test .
          
          docker run -d --name dca-phpinfo academiaonline/dca-phpinfo:test
          
          while true
            do
              sleep 10
              docker logs dca-phpinfo 2>& 1 | grep 'PHP .* Development Server .* started' && break
            done
            
  swarm:
    runs-on: ubuntu-18.04
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: test
        run: |
        
          set -x
          
          docker swarm init
          
          docker build -t academiaonline/dca-phpinfo:test .
          
          sed -i s/worker/manager/  etc/swarm/manifests/dca-phpinfo.yaml
          sed -i s/latest/test/     etc/swarm/manifests/dca-phpinfo.yaml
          docker stack deploy -c    etc/swarm/manifests/dca-phpinfo.yaml dca-phpinfo
          
          while true
            do
              sleep 10
              docker service logs dca-phpinfo_dca-phpinfo 2>& 1 | grep 'PHP .* Development Server .* started' && break
            done
            
  kubernetes:
    runs-on: ubuntu-18.04
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: test
        run: |
        
          set -x
          
          version="1.18.10-00"
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -                                                     ;
          echo deb http://apt.kubernetes.io/ kubernetes-xenial main | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y --allow-downgrades kubelet=$version kubeadm=$version kubectl=$version
          ip=$( ip r | grep default | awk '{ print $9 }' )
          sudo swapoff -a
          sudo kubeadm init --apiserver-advertise-address $ip --pod-network-cidr=192.168.0.0/16 --ignore-preflight-errors=all
          mkdir -p $HOME/.kube
          sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config
          sudo chown $(id -u):$(id -g) $HOME/.kube/config
          echo "source <(kubectl completion bash)" >> ~/.bashrc
          kubectl apply -f https://docs.projectcalico.org/v3.16/manifests/calico.yaml
          master=$( kubectl get node | grep master | awk '{ print $1 }' )
          kubectl taint node $master node-role.kubernetes.io/master:NoSchedule-
          
          docker build -t academiaonline/dca-phpinfo:test .
          
          sed -i s/latest/test/ etc/kubernetes/manifests/dca-phpinfo.yaml
          kubectl apply -f      etc/kubernetes/manifests/dca-phpinfo.yaml
          
          while true
            do
              sleep 10
              kubectl logs svc/dca-phpinfo
              kubectl logs svc/dca-phpinfo 2>& 1 | grep 'PHP .* Development Server .* started' && break
            done
